version: "2"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_USER: "xiaoguo"
      MYSQL_PASSWORD: "123123"
      MYSQL_ROOT_PASSWORD: "123123"
    volumes:
        - ./mysql/data/:/var/lib/mysql/:rw
        - ./mysql/logs/:/var/log/mysql/:rw
        - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
  redis:
    image: redis:3.2
    container_name: redis
    restart: always
    ports:
        - 6379:6379
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    privileged: true
    ports:
        - 80:80
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/logs:/var/log/nginx
    links:
        - php

  php:
    image: php:7.2-fpm
    restart: always
    container_name: php
    ports:
        - "9000:9000"
    volumes:
        - ./www:/data/wwwroot
    links:
        - mysql
        - redis
  beanstalkd:
    image: schickling/beanstalkd
    restart: always
    container_name: beanstalkd
    ports:
      - "11300:11300"
    depends_on:
      - php
  composer:
    image: composer/composer:latest
    volumes:
    #网站目录
      - ./app:/app:rw
    working_dir: /app/webroot
    command: composer install
  node:
    image: node:8
    container_name: node.js
    ports:
      - "8888:8888"
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./node/node_modules:/usr/src/app/node_modules
      - ./node/nodejs:/usr/src/app
